# Generated by Django 2.2.6 on 2020-02-01 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_profile_avatar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collectrecord',
            options={'ordering': ['id']},
        ),
    ]
